# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e4803bfed97fba9a19d4497e9f05ccbc3f95b61fec98c0118eac595848b398d6b9d45d4ee60f137db34dcc63567cb68408581bf14e668e769c06b9c13cab9a

test:
  secret_key_base: 26eaf0d227037353d90eb5e489e6f70aa3ac4afc56144c25db704e747f54df3e4cfe5013d942bd4df5808d16fcb34b474feea20222bc75080a9d2e9459888958

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
